### ISSUE TITLE
When changing the node url, the API key is not saved

### ISSUE THREAD

**Issue by Te-k** [phishdetect/phishdetect-extension#37]
If I change the url of the node, the API key I give is not saved.

How to reproduce:
* Go in settings
* Update both the node url to a new node and add the API key
* Save
* Then I get the error message "This PhishDetect Node requires users to register a secret token."
* When clicking on it, I see that it saved the url of the node but not the key

I had this issue with the last commit 179e0f618b871d05c5f6d88dac99a08a9749b765

**Comment by DonnchaC** [comment]
Fixed in #40
